# n=int(input("Digite um número, para que seja calculado sua tabuada: "))
# print(n,'x 01 = ', (n * 1))
# print(n,'x 02 = ', (n * 2))
# print(n,'x 03 = ', (n * 3))
# print(n,'x 04 = ', (n * 4))
# print(n,'x 05 = ', (n * 5))
# print(n,'x 06 = ', (n * 6))
# print(n,'x 07 = ', (n * 7))
# print(n,'x 08 = ', (n * 8))
# print(n,'x 09 = ', (n * 9))
# print(n,'x 10 = ', (n * 10))

#forma 2
n=int(input("Digite um número, para que seja calculado sua tabuada: "))
print('{} x {}  = {}'.format(n, 0, n*0))
print('{} x {}  = {}'.format(n, 1, n*1))
print('{} x {}  = {}'.format(n, 2, n*2))
print('{} x {}  = {}'.format(n, 3, n*3))
print('{} x {}  = {}'.format(n, 4, n*4))
print('{} x {}  = {}'.format(n, 5, n*5))
print('{} x {}  = {}'.format(n, 6, n*6))
print('{} x {}  = {}'.format(n, 7, n*7))
print('{} x {}  = {}'.format(n, 8, n*8))
print('{} x {}  = {}'.format(n, 9, n*9))
print('{} x {} = {}'.format(n, 10, n*10))

